version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  groups:
    actions:
      patterns:
      - '*'
  ignore:
  - dependency-name: hashicorp/setup-terraform
    update-types:
    - version-update:semver-major
  - dependency-name: terraform-linters/setup-tflint
    update-types:
    - version-update:semver-major
